apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
        {{- include "outline.selectorLabels" . | nindent 6 }}