version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6378:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
  s3:
    image: lphoward/fake-s3
    ports:
      - "127.0.0.1:4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
  outline:
    image: docker.io/outlinewiki/outline
    depends_on:
      - postgres
      - redis
      - s3
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - SECRET_KEY=77a0c87fbaffa6453f447d6cf798dc8895c8776496ab2dd49fd4454a91293775
      - UTILS_SECRET=053a1c76063701938dac869291d36b29d4e0a1c08ada34658452d1a2cae5a803
      - PGSSLMODE=disable
      - DATABASE_URL=postgres://user:pass@postgres:5432/outline
      - DATABASE_CONNECTION_POOL_MIN= 4
      - DATABASE_CONNECTION_POOL_MAX= 4
      - REDIS_URL=redis://redis
      - URL=http://localhost:3000
      - PORT=3000
      - FORCE_HTTPS=false
      - AWS_S3_UPLOAD_BUCKET_URL=http://s3:4569
      - AWS_S3_UPLOAD_BUCKET_NAME=bucket_name_here
      - DEBUG=cache,presenters,events,emails,mailer,utils,multiplayer,server,services
