name: Run Database Migrations
on:
  workflow_dispatch:
jobs:
  push-to-ecr:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ecs run-task \
            --network-configuration 'awsvpcConfiguration={subnets=["subnet-05e32ecbded5e2ae5","subnet-0b5d566d833fc299b","subnet-0f7d5427fc224cff7","subnet-026b18555f09c839c","subnet-03797aa3fb79ecd79","subnet-0a78941296d093e01"],securityGroups=["sg-0e8fd07f882ae0dcb"],assignPublicIp=DISABLED}' \
            --cluster arn:aws:ecs:us-east-1:859601545600:cluster/prod \
            --task-definition outline-migrations:1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
