name: Run Database Migrations
on:
  workflow_dispatch:
jobs:
  push-to-ecr:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ecs run-task \
            --network-configuration 'awsvpcConfiguration={subnets=["subnet-01789cc05fce856d7","subnet-06f6b115670f84dde","subnet-0a5fc02992eeb827d","subnet-04b2c16f04f2d4ee1","subnet-06c6f8e240f50068b","subnet-0f4c916b0d8f2e705"],securityGroups=["sg-016cfb507877021b7"],assignPublicIp=DISABLED}' \
            --cluster arn:aws:ecs:us-east-1:928151643990:cluster/prod \
            --task-definition outline-migrations:1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
