name: Push Outline To ECR
on:
  workflow_dispatch:
jobs:
  push-to-ecr:
    name: Push Outline To ECR
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker pull docker.io/outlinewiki/outline:latest
          docker tag docker.io/outlinewiki/outline:latest 564772533787.dkr.ecr.us-east-1.amazonaws.com/outline:latest
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 564772533787.dkr.ecr.us-east-1.amazonaws.com
          docker push 564772533787.dkr.ecr.us-east-1.amazonaws.com/outline:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
